### ISSUE TITLE
RTL support is missing on month/year buttons and prev buttons is smaller than next

### ISSUE THREAD

**Issue by dariusjb** [beenote/angular-material-datetimepicker#10]
From the demo, you can switch to RTL and you can see the buttons to change month or year are wrongly oriented and wrongly aligned

I thought the align should be fixed, but simply adding the below css rules fixes the issue:

[dir=rtl] .dtp  div.dtp-year-btn-next, [dir=rtl] .dtp  div.dtp-month-btn-next, 
[dir=rtl] .dtp  div.dtp-year-btn-next, [dir=rtl] .dtp div.dtp-month-btn-prev {
	-ms-transform: rotate(180deg); /* IE 9 */
   	-webkit-transform: rotate(180deg); /* Chrome, Safari, Opera */
    	transform: rotate(180deg);
}

It should probably be declared as another issue, but the arrows for prev and next buttons are differents.
Still from the demo, I have for prev arrows: &#x25C0; and for next arrows: &#x25BA;
Their are different type of arrows that can be represented with hexa code. The smaller one is normally an arrow inside a square.
I would suggest using the corresponding 	&#x25C4;  which is the arrow pointing left, but of the same size and render of the one used for next.
Unless it is by design to have prev smaller?

Regards,

**Comment by hexadecy** [comment]
@dariusjb Is this ok ? https://beenote.github.io/angular-material-datetimepicker/

**Comment by hexadecy** [comment]
https://github.com/beenote/angular-material-datetimepicker/tree/v1.6.7

**Comment by hexadecy** [comment]
Fixed

**Comment by dariusjb** [comment]
thks
