### ISSUE TITLE
Add orientation support in respect of the material designs guidelines for picker

### ISSUE THREAD

**Issue by dariusjb** [beenote/angular-material-datetimepicker#11]
As a new feature, I would like the support of material design guideline when orientation changes

See:
https://material.io/guidelines/components/pickers.html

I would be able to propose a new template for the support but I am not sure the current template declaration allows any overwrite.

**Comment by hexadecy** [comment]
Since Angular Material 1.1.4 they added to $mdMedia landscape and portrait. This should only be used for mobile, as $mdMedia is called on each small resize of the window.

**Comment by hexadecy** [comment]
Maybe not that useful.
