### ISSUE TITLE
Adding Minute steps does not produce expected result

### ISSUE THREAD

**Issue by khayargoli** [beenote/angular-material-datetimepicker#16]
When setting 15 minutes of step, the minutes that can be selected are 00 - 15 - 30 - 45, but this does not go expected, any minute can be set.

Preview at : https://stackoverflow.com/questions/45864678/set-minute-steps-on-mdpicker-library-angularjs

**Comment by hexadecy** [comment]
You mean when the value is set in the ng-model?
As a workaround:
```
var newDate = new Date();
newDate.setMinutes(15 * Math.round(newDate.getMinutes() / 15));
newDate.setSeconds(0);
newDate.setMilliseconds(0);
$scope.dateTime = newDate;
```

What first value do you use? or want?
I can probably round the init value and the fallback to the nearest step.

**Comment by hexadecy** [comment]
@biswas123 can you try with 1.8.7?

**Comment by khayargoli** [comment]
Hi hexadecy,

I still have this problem on latest built.

**Comment by hexadecy** [comment]
@biswas123 please copy part of your html and js code here, I don't see how to reproduce it on 1.9.2. Do you use Bower or Npm?

**Comment by hexadecy** [comment]
I have added an example for your case : https://beenote.github.io/angular-material-datetimepicker/
```
<md-input-container>
<label>Timepicker Only | 12-hour | step 15 | auto-ok</label>
<input mdc-datetime-picker date="false" time="true" 
    placeholder="Time" minutes="true" minute-steps="15"
    min-date="minDate" auto-ok="true" type="text" id="time15" 
    format="hh:mm a" short-time="true"
    ng-model="time">
</md-input-container>
```

Can you reproduce it with this?

**Comment by hexadecy** [comment]
@biswas123 resolved? I will close this issue if I don't have more info...
