### ISSUE TITLE
Do not call ng-change method

### ISSUE THREAD

**Issue by jasondiazg** [beenote/angular-material-datetimepicker#22]
I have been using your fork for a few months now. Everything works well, but today I found a problem with the ng-change method.

I have the following HTML:
`<input mdc-datetime-picker ng-model="vm.valueModel" ng-change="vm.runOnChangeTrigger()"/>`

And the following JS:
`vm.runOnChangeTrigger = function() {
       if (vm.onChange)
           vm.onChange( { value: vm.valueModel } );
  }`

Where vm.runOnChangeTrigger() is a method in my scope. The problem is that this method does not execute when the value changes. Have you tried it? Thanks for you response.

**Comment by hexadecy** [comment]
ng-change is used on our production site since 25 Apr 2016.
I'm not sure what you try to do with vm.onChange? Why do you pass an object with a value that is already accessible anywhere in your current scope?

Try with:
`<input mdc-datetime-picker ng-model="vm.valueModel" ng-change="vm.alert('changed')">`

In your controller:
```
vm.alert = function(message) {
    window.alert(message);
    console.log(vm.valueModel);
};
```

**Comment by hexadecy** [comment]
I also added `ng-clear="expression"` in 1.9.7, because if the date value is cleared to undefined or not changed, `ng-change` does not trigger. `ng-clear` must be used with the X icon from `show-icon=true`.

**Comment by jasondiazg** [comment]
The vm.onChange is a binding of the component that manage your input mdc-datetime-picker. If the programmer add the binding on-change, I invoke this from the ng-change method in the component. But do not pay attention to this at the moment.

Thank you for ng-clear! I will be testing this and I will tell you the results...

**Comment by hexadecy** [comment]
I found a bug, if the date is manually cleared (keyboard delete) when in `edit-input="true"`, ng-change or ng-clear is not called.

Probably related to this check:

    if (!moment(scope.currentDate).isSame(options.currentDate)) {       
        $timeout(scope.ngChange, 0);
    }

**Comment by jasondiazg** [comment]
Exactly that is the error that I have. The date is written directly by the user. Any idea for resolve this?

**Comment by hexadecy** [comment]
As a workaround, in your controller (inject $scope), then:
```
$scope.$watch(function() {
   return vm.valueModel;
}, function(newValue, oldValue) {
   // do something
});
```
ng-change normally does not evaluate the expression when the value change is coming from the model, in our case from the user keyboard.

**Comment by jasondiazg** [comment]
thank you @hexadecy! This works for me. It's closed.

**Comment by hexadecy** [comment]
I can release a new version with:
```
scope.$watch('currentDate', function(newVal, oldVal) {
   if (newVal != oldVal) $timeout(scope.ngChange, 0);
});
```
In that case ng-clear will be useless I think.

**Comment by hexadecy** [comment]
@jasondiazg do you still use ng-clear?, I think I will call a ngChange on clear and also when the date go to undefined.

**Comment by jasondiazg** [comment]
Go ahead, you can remove ng-clear if you wish! I'm not really using it. Thank you for your help.
