### ISSUE TITLE
Keep bounded data type?

### ISSUE THREAD

**Issue by j-walker23** [beenote/angular-material-datetimepicker#25]
Hey, thanks for this awesome fork.

Just was curious if it was currently possible for the ng-model to stay a moment data type if that is the initial type given.
When i pass a object to the directive that is a moment object, then use it to change the date/time. My bound ng-model changes to a native Date. Is there anyway around that? Hoping i am just missing something.

**Comment by hexadecy** [comment]
@j-walker23 you are right. Easiest way to check: `{{date._isAMomentObject}}`

._d is the internal date of moment.
```
$mdDialog.show(dialogOptions).then(function(v) {
   scope.currentDate = v ? v._d : v;
```

Do you know why ?

**Comment by j-walker23** [comment]
I don’t know why. Is it backwards compat reasons?

**Comment by j-walker23** [comment]
Actually, i think i might have a feature request after looking at the code. If i pass a moment utc value in, then the object returned after date/time selection stay in utc.

This came up from giving the directive a utc moment object. Then after an edit through the directive is made, the date shown gets shifted by whatever my timezone offset is. Confusing the user who selected a time, and then is displayed what might seem like a different random time. Guessing that would be new functionality.

I can handle conversions with ng-change. Just thought i would bring it up. Thanks again.

**Comment by hexadecy** [comment]
@j-walker23 can you test it?

Yes it's a bug and can be confusing.
Now if a moment utc is passed it will stay as passed.
Do not use with `edit-input="true"` for now.

Since version 1.0, logbon72 chose to return a js date, but returning a moment (local) can also be done.

**Comment by j-walker23** [comment]
Damn, i just saw this. Thank you, I will test it today!

**Comment by j-walker23** [comment]
Worked perfectly. Thank you!
