### ISSUE TITLE
Add validation for input with format

### ISSUE THREAD

**Issue by andreyjkee** [beenote/angular-material-datetimepicker#30]
When format, for example, is M/D/YY, I can input value like 8/18/18qwerty, and there are no form validation errors, but in $ngModelValue we have undefined. I think we should provide the error in form.$error object when invalid format takes place.

**Comment by hexadecy** [comment]
Which $error type to set? 'date-format' ?
```
ngModel.$setValidity('date-format', moment(value, scope.format).isValid());
```

**Comment by andreyjkee** [comment]
yes, I think `date-format` or simply `format` word will be fine, like min/max errors

at this moment I  have workaround in my code where I use `format` keyword for $errors
`
this.form.date.$setValidity("format", moment(this.form.date.$viewValue, scope.format).isValid());
`

**Comment by andreyjkee** [comment]
And additional note `moment('4/30/19dd', 'M/D/YY').isValid()` for example, returns true. I think it is wrong, we need to make moment use strict parsing, `moment('4/30/19dd', 'M/D/YY', true).isValid()`

**Comment by hexadecy** [comment]
I think strict parsing is a good idea in this case.

**Comment by andreyjkee** [comment]
@hexadecy Works for now, thank you.
Waiting for npm release :)
