### ISSUE TITLE
timezone option applied only in dialog mode

### ISSUE THREAD

**Issue by andreyjkee** [beenote/angular-material-datetimepicker#31]
Hi!
I found issue with timezone option,
timezone applied only for dialog mode, I think it needs to be applicable also when edit-input is true.
So we need to apply utcOffset also when ngModelChange takes place

**Comment by hexadecy** [comment]
You mean when the time is in a format like `06:35 am +02:00`.
Yes, I didn't implement it with edit-input yet.

**Comment by andreyjkee** [comment]
Works now

**Comment by hexadecy** [comment]
- Not working for offset `'utc' : 0`
- Converted to normal JS date instead of staying as moment._isUTC in this special case.
- When changing manually it will shift to a different point in UTC, passing `false `to utcOffset it will only change the local time and stay in the correct time zone.

**Comment by hexadecy** [comment]
You can use the third example to test that: https://beenote.github.io/angular-material-datetimepicker/

**Comment by hexadecy** [comment]
@andreyjkee it is now published on npmjs. Thanks for you work on this.

**Comment by andreyjkee** [comment]
@hexadecy thank you for active collaboration on this change.
I found some issue in my use cases: https://github.com/beenote/angular-material-datetimepicker/commit/9c5d55029eabfccf4d4a5f57aeaf5c06e957a287?diff=split#r28729853 (see comment)

**Comment by hexadecy** [comment]
Maybe you are offsetting the time with a $watch somewhere in your code.
When I init the date with moment.utc() it changed nothing in my third example case.
I need more info, your template? an example? step by step to reproduce.

**Comment by andreyjkee** [comment]
I create the date with offset (which comes from user stored setting on server, for example "+0000" for London.
ng-models is:
`
date = moment().utc().utcOffset(this.gmtOffset);
`
format comes from user settings, in this case it is M/D/YY hh:mm
And i display date with moment(date).format('M/D/YY hh:mm')
time displayed in input in my local timezone, instead of offset
If i change m.utcOffset(offset, false) to m.utcOffset(offset, true), that work as expected.
I can try to reproduce this in simple example if you can share jsdiffle (or analog) with this lib included.

**Comment by hexadecy** [comment]
Try with:
`date = moment().utcOffset(this.gmtOffset);`
But there is no DST when using this.

**Comment by andreyjkee** [comment]
I tried, without utc() call problem is stay

**Comment by hexadecy** [comment]
Ok it was a problem with the parsing format. I was using the **Z** in my example.

**Comment by hexadecy** [comment]
https://github.com/beenote/angular-material-datetimepicker/releases/tag/v1.15.1

**Comment by andreyjkee** [comment]
@hexadecy awesome, thank you! now works as expected!
