### ISSUE TITLE
How to import module in angular 5

### ISSUE THREAD

**Issue by KashyakSupport** [beenote/angular-material-datetimepicker#37]
angular.module('myAwesomeModule', [
      //other dependencies ignored
      'ngMaterialDatePicker'
    ]);

**Comment by KashyakSupport** [comment]
https://stackoverflow.com/questions/50385520/how-to-import-module-for-ng-material-datetimepicker-in-angular-5

**Comment by andreyjkee** [comment]
@KashyakSupport this module is for angularjs, you can't use it with angular

**Comment by KashyakSupport** [comment]
Is there any datetimepicker package for angular material?

**Comment by andreyjkee** [comment]
@KashyakSupport I think you need this: https://material.angular.io/components/datepicker/overview

**Comment by hexadecy** [comment]
https://github.com/DanielYKPan/date-time-picker The most complete package to date
https://github.com/owsolutions/amazing-time-picker Only the time picker

This is strange, Google killed the Material specs page for pickers : https://material.io/guidelines/components/pickers.html
