### ISSUE TITLE
Add $watchers for min and max date

### ISSUE THREAD

**Issue by andreyjkee** [beenote/angular-material-datetimepicker#38]
In my use case I have two related inputs, where first is start date, and second is end date. Min for end date is set as start date + 1 day, but validation triggered only if second input changed manually.
I add additional code to figure out this problem.
```
              if (scope.minDate) {
                  scope.$watch(function () {
                    return scope.minDate;
                  }, function (val2, val1) {
                      if (val2 !== val1) {
                          ngModel.$setValidity('min', !scope.currentDate.isBefore(scope.minDate));
                      }
                  });
              }
```
and for maxDate
```
              if (scope.maxDate) {
                  scope.$watch(function () {
                      return scope.maxDate;
                  }, function (val2, val1) {
                      if (val2 !== val1) {
                          ngModel.$setValidity('max', !scope.currentDate.isAfter(scope.maxDate));
                      }
                  });
              }
```
@hexadecy could you add this to package?

**Comment by hexadecy** [comment]
@andreyjkee, I don't want to add too much watchers. I think you can also use ng-change for that...

**Comment by andreyjkee** [comment]
@hexadecy you mean calling $setValidity manually for all dependent fields? I think its not better approach

**Comment by hexadecy** [comment]
@andreyjkee ok can you make a PR for this?

**Comment by andreyjkee** [comment]
@hexadecy sure, created

**Comment by hexadecy** [comment]
Ok, I will do more testing before releasing a new version.

**Comment by hexadecy** [comment]
Does not work when there are more than 2 date time pickers.
Also in some case, scope.currentDate is not always a moment object.
Maybe we have to look at $validators and $validate()...

**Comment by andreyjkee** [comment]
@hexadecy which error you have (when more than 2 date time pickers)?

**Comment by hexadecy** [comment]
With the demo of this project.
```
(6) angular.js:14961 TypeError: scope.currentDate.isBefore is not a function
    at angular-material-datetimepicker.js:209
    at m.$digest (angular.js:18543)
    at angular.js:18835
    at e (angular.js:6439)
    at angular.js:6718
```

**Comment by hexadecy** [comment]
I don't want to add another watcher.
