### ISSUE TITLE
Module 'ngMaterialDatePicker' is not available!

### ISSUE THREAD

**Issue by nidhinkumar06** [beenote/angular-material-datetimepicker#41]
Module 'ngMaterialDatePicker' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

When i run the code in dev-mode it works fine when i try to build the app using gulp serve: dist it shows me the error like mentioned above

**Comment by hexadecy** [comment]
@nidhinkumar06 There was no gulp serve task.
To build `gulp` or `gulp default`

**Comment by hexadecy** [comment]
I was using lite-server, I've just added some shortcuts:
```
npm run dev
yarn run dev
gulp serve
```

It's based on browser-sync and served me pretty well for AngularJS app.
