### ISSUE TITLE
Timezone issue on ng-model bind

### ISSUE THREAD

**Issue by tux1337** [beenote/angular-material-datetimepicker#42]
I have a web formular which loads previously saved values to a datetimepicker field. 

When I bind the saved value to the ng-model of the field, for example:
`2018-06-07T21:15:00.000Z`
it is shown as UTC in the formular and is not calculated to my timezone which it works when I pick it over the picker dialog. 

If I save this value once more, it is calculated from my current timezone to a UTC value which changes the loaded value (in my case) to: 
`2018-06-07T19:15:00.000Z`

Implementation of the field:
`<input 
                            mdc-datetime-picker 
                            date="true"
                            time="true"
                            type="text"
                            id="time"
                            short-time="true"
                            placeholder="soon as possible"
                            click-outside-to-close="false"
                            auto-ok="true"
                            min-date="StartTimeMinDate"
                            max-date="StartTimeMaxDate"
                            format="YYYY-MM-DD HH:mm"
                            ng-model="MigrationData.StartTime"
                            edit-input="false"
                            show-icon="true"
                            ng-model-options="{lang: 'en'}"
                            ></input>`

The issue is reproducable with 
 	version 1.15.2 
 	version 1.15.1

The behaviour doesn't change if I add the "timezone: 'utc'" attribute to ng-model-options. 
My expectation of this option is, that the value in the field is UTC. But also with this option the value is local time.

**Comment by tux1337** [comment]
I was able to solve it: 
You have to use format="YYYY-MM-DD HH:mm**Z**"

This was not clear for me after studying the documentation. Maybe we can improve this in the readme.

**Comment by hexadecy** [comment]
@tux1337 can you please make a suggestion to improve the readme?

**Comment by hexadecy** [comment]
Readme improved
