### ISSUE TITLE
Validation not triggered when using edit-input and datepicker

### ISSUE THREAD

**Issue by andreyjkee** [beenote/angular-material-datetimepicker#43]
For reproduce set min-date, then write one month before this date, an error is shown. Then click to Icon and open Calendar, then select min available date (picker will close (why?)), error still present, because $setValidity was not triggered.

For picker close issue maybe this fix can be applied:
```javascript
              if (date) {
                if (calendar.isSelectedDay(date)) {
                  return picker.ok();
                }
                picker.selectDate(moment(date).hour(calendar.date.hour()).minute(calendar.date.minute()));
                if (picker.params.autoOk) {
                  picker.ok();
                }
              }
```
need to replace with:
```javascript
              if (date) {
                if (!calendar.isSelectedDay(date)) {
                 picker.selectDate(moment(date).hour(calendar.date.hour()).minute(calendar.date.minute()));
                }
                if (picker.params.autoOk) {
                  picker.ok();
                }
              }
```

**Comment by hexadecy** [comment]
What I have when I open the calendar, is the min date. The picker never close by itself.
What do you have in the console log?

**Comment by hexadecy** [comment]
@andreyjkee I cannot reproduce this issue so I cannot fix it. 
Can you provides me a demo or a detailed step by step.

**Comment by hexadecy** [comment]
Cannot reproduce, reopen with more info.
