### ISSUE TITLE
mixing manual entry and calendar leads to invalid date format

### ISSUE THREAD

**Issue by francois-bernard-bouissieres** [beenote/angular-material-datetimepicker#45]
In case we have the edit-input in the component, mixing manual entry and calendar leads to invalid date format:

To reproduce: 
-	input the date and the time manually (with correct format)
-	delete the date and the time manually (not with the cross)
-	choose a date and a hour in the date-picker.

==> Component is in invalid date format state

**Comment by hexadecy** [comment]
Ok I see, choosing the date in the picker don't set the date format valid.
