### ISSUE TITLE
Cant get .js.map to load

### ISSUE THREAD

**Issue by Jensenj010** [beenote/angular-material-datetimepicker#46]
I am running a MEAN stack environment, and ran into an issue.
Granted, this is probably me doing something wrong and not a true issue with the code.

We have a PUG template acting as our main view, and are declaring all dependencies there. In it, I have these lines:

```
script(type="text/javascript" src="scripts/ng-material-datetimepicker/dist/angular-material-datetimepicker.min.js")
script(type="text/javascript" src="scripts/ng-material-datetimepicker/dist/angular-material-datetimepicker.min.js.map")
link(rel="stylesheet" href="scripts/ng-material-datetimepicker/dist/material-datetimepicker.min.css")
```
the scripts portion of the src is set to our node-modules folder using this line:

`app.use('/scripts', express.static(path.join(__dirname, ".\\node_modules")));`
With that setup, I am getting the following error in the dev console, in reference to the .js.map file only (everything else seems to work):

`Uncaught SyntaxError: Unexpected token :`
I have seen some answers regarding the MIME type being incorrect, or this being an issue with chrome, but as I mentioned, I'm starting to lean towards something of mine being set up incorrectly. What am I doing wrong?

**Comment by hexadecy** [comment]
Don't add the js.map at all and don't specify the type for javascript.
The browser will use the same path as for .js
```
<script src="scripts/ng-material-datetimepicker/js/angular-material-datetimepicker.js"></script>
<link rel="stylesheet" type="text/css" href="scripts/ng-material-datetimepicker/css/material-datetimepicker.css">
```

**Comment by Jensenj010** [comment]
It works! Thanks a lot :)
