### ISSUE TITLE
Max date does not allow valid values to be selected

### ISSUE THREAD

**Issue by ajmueller** [beenote/angular-material-datetimepicker#47]
**Library Versions:**
- AngularJS: 1.7.2
- Angular Material: 1.1.10
- Angular Material Datetimepicker: 1.17.0
- Moment.js: 2.22.2

**Reproduction Steps**
1. Set a `max-date` property for a datetimepicker to be 12:50pm.
2. Try to change that datetimepicker's time to 12:00pm.
3. You can change the hour to 12 and the minutes to 0, but the PM button is disabled, despite being a valid option.

I have reproduced the issue with a [Plunker](https://next.plnkr.co/plunk/YnDIO0lqZY7OT10K).

**Comment by hexadecy** [comment]
@ajmueller Can you please confirm me it's ok with v1.17.1

**Comment by ajmueller** [comment]
@hexadecy I've updated my Plunker and it's working great!  I've also updated our main application and it's working great there, too.  Thanks for such a quick turnaround!

**Comment by hexadecy** [comment]
Always easier to fix when there is a demo. Good works.

**Comment by ajmueller** [comment]
Thanks, glad to help!  This project is incredibly important for us at my job, so I'm happy that someone is still maintaining it.
