### ISSUE TITLE
Jalali calendar

### ISSUE THREAD

**Issue by shdehnavi** [beenote/angular-material-datetimepicker#49]
Hi,
How to convert this datepicker to jalali persian calendar ?

**Comment by hexadecy** [comment]
You can fork this project or make a pull request.

**Comment by hexadecy** [comment]
[Jalali calendar](https://en.wikipedia.org/wiki/Jalali_calendar) or
[Solar Hijri calendar](https://en.wikipedia.org/wiki/Solar_Hijri_calendar)
The Jalali seems hard to implement.

**Comment by shdehnavi** [comment]
you can merge it with jalali pre-built repositories, its' not necessary to build it from the first and develope jalali system from first.

ty
