### ISSUE TITLE
Delay in open modal when using with android app webview

### ISSUE THREAD

**Issue by arjundas** [beenote/angular-material-datetimepicker#50]
I am using this module in my angularjs app which is load from android application webview.

all works fine when i open this app from browser, the modal is open as soon as click on input element, but when i load it from webview of android app it takes almost 3-4 seconds to open modal.

my input elements is as follows 
```
<input
     time="false"
     date="true"
     mdc-datetime-picker=""
     type="text"
     id="from_date"
     click-outside-to-close="true"
     show-todays-date=""
     today-btn="false"
     ng-model="filter.from_date"
     format="DD-MM-YYYY"
     disable-parent-scroll="true"
     min-date="minDate"
     max-date="maxDate"
     readonly />
```

Any help regarding this?

**Comment by hexadecy** [comment]
Angularjs version? , android device used?, emulator or real?...

**Comment by arjundas** [comment]
Angularjs version 1.5.8
Android version 5.1 ( lollipop )
Android device : Micromax Q465 ( real )

**Comment by hexadecy** [comment]
This is strange.
In the demo: https://beenote.github.io/angular-material-datetimepicker/, the two first picker sometimes open slower 2-3 seconds the first time only.
I used http://flatteredwithflutter.com/webview-in-flutter/ on a Pixel 2 Android Emulator.

Do they perform better for you?:
https://material.angularjs.org/latest/demo/datepicker

Maybe it's related to the use of css getComputedStyle in this lib.

**Comment by arjundas** [comment]
Yes, a native datepicker of angularjs material works speedy but its not provide a pop view for datepicker.

**Comment by hexadecy** [comment]
Have you try with `show-icon="true"`. It seems slower with just the input.
