### ISSUE TITLE
Current year is not available in dropdown when we have restricted user to select future date

### ISSUE THREAD

**Issue by sonusindhu** [beenote/angular-material-datetimepicker#51]
Hi,

Firstly, we want to thankyou for this superb datepicker.

I am getting an issue and scenario is once I restricted user to not select the future date, then user can't able to select the current year from the dropdown. I am attaching screenshot what I mean to say so you can understand properly.

![image](https://user-images.githubusercontent.com/4919309/51601513-94f9d800-1f2a-11e9-9113-4ba5e55bf78a.png)

Could you please review and let me know how we can show the current year to the YEAR dropdown so we can select any past(fine now) or current year.

Thanks

**Comment by hexadecy** [comment]
Please let me know if v1.17.2 version fix your issue.

**Comment by sonusindhu** [comment]
Thank You @hexadecy for quick fix. It works fine now.
