### ISSUE TITLE
Time issue AM/PM if future date is restricted

### ISSUE THREAD

**Issue by sonusindhu** [beenote/angular-material-datetimepicker#54]
Hi,

Thanks for the great plugin, I am facing issue which I describe step by step and let me know if you need more clarity.

1.	Select the Any date expect the today date
 
![step1](https://user-images.githubusercontent.com/4919309/52255428-8521c100-2938-11e9-8428-49561040edda.png)

2.	Select PM from AM/PM buttons
 
![step2](https://user-images.githubusercontent.com/4919309/52255436-894dde80-2938-11e9-953e-1717f70ddc16.png)

3.	Now Click on Cancel Button and Select Today’ date
 
![step3](https://user-images.githubusercontent.com/4919309/52255438-8c48cf00-2938-11e9-9f53-717335d82a7d.png)

4.	Observe the issue that you will not able to select time and click on AM is also disabled
This happens only in the morning time when PM time is not yet available to select

**Comment by hexadecy** [comment]
What is your maxDate? now?
Today button also set it to now, but it will be after maxDate is time pass.

**Comment by sonusindhu** [comment]
Yes, I have maxDate is now.

**Comment by hexadecy** [comment]
Ok it was two checks missing for the selected date, it also affected the today button.
Thank you, it was a bug really hard for me to reproduce, I only work the afternoon ;)

**Comment by sonusindhu** [comment]
@hexadecy Is this fixed?

**Comment by hexadecy** [comment]
@sonusindhu yes in [v1.18.1](https://github.com/beenote/angular-material-datetimepicker/releases/tag/v1.18.1). Can you confirm it's ok and close this issue?

**Comment by sonusindhu** [comment]
Thanks @hexadecy 
It seems fixed now.
