### ISSUE TITLE
ng-model not working

### ISSUE THREAD

**Issue by kadirguloglu** [beenote/angular-material-datetimepicker#56]
angularjs version : 1.7.7
angular-material-datetimepicker version : 1.18.3
moment version : 2.24.0

angularjs ng-model attributes is not working. 
`
<input mdc-datetime-picker="" today-text="Bugün" am-text="ÖÖ" pm-text="ÖS" cancel-text="İptal" ok-text="Tamam" date="true" time="true" type="text"
                                           placeholder="Başlangıç tarihi" show-todays-date="true" minutes="true" min-date="date" auto-ok="true"
                                           short-time="true" ng-model="RezervationModel.StartDate" name="StartDate" class="md-input" required>
`

Thanks.

**Comment by hexadecy** [comment]
I cannot reproduce it, what is the error message?
How did you initialize `"RezervationModel.StartDate"`?

**Comment by hexadecy** [comment]
@kadirguloglu did you found something on your side?

**Comment by tw1nk** [comment]
I have the same issue. 
The form should be invalid if the date isn't set.

**Comment by hexadecy** [comment]
Ok I see there is no required in the demo page.

**Comment by hexadecy** [comment]
@tw1nk can you test with this commit please: https://github.com/beenote/angular-material-datetimepicker/commit/46e138c68a24133dbe561a4d8f4e2bcd2f0bff4a.

**Comment by tw1nk** [comment]
I'll try it tomorrow when i'm back at work.

**Comment by hexadecy** [comment]
@tw1nk any issue?

**Comment by hexadecy** [comment]
Reopen if not fixed
