### ISSUE TITLE
Not loading properly on small screen size

### ISSUE THREAD

**Issue by sonusindhu** [beenote/angular-material-datetimepicker#57]
Hi,
Could you please check as I am facing issue on small screen size as picking popup is not loading properly on small screen size as well as once we have debugger window open.

![small screen size](https://user-images.githubusercontent.com/4919309/54031995-5ff1ce00-41d6-11e9-9363-b27a1969752c.png)

Please review and let me know if you need any clarification.

Thanks

**Comment by hexadecy** [comment]
@sonusindhu I cannot reproduce that with the demo page:
![small screen DateTimePicker](https://user-images.githubusercontent.com/10960108/54079877-48d4de00-42b3-11e9-866d-156840242ad1.png)

It will center with the document body: 
https://github.com/beenote/angular-material-datetimepicker/blob/gh-pages/js/angular-material-datetimepicker.js#L248

**Comment by sonusindhu** [comment]
You are right. not an issue
Thanks
