### ISSUE TITLE
Support for Angular >= 2

### ISSUE THREAD

**Issue by vladimirsvicevicsrb** [beenote/angular-material-datetimepicker#59]
Hi, is there any chance to create the same component for Angular >= 2, or there is already implemented component similar to yours?
Thanks

**Comment by hexadecy** [comment]
No clock: https://material.angular.io/components/datepicker/overview
Complete but not material themed: https://github.com/DanielYKPan/date-time-picker
Just the clock: https://github.com/owsolutions/amazing-time-picker


I do not personally have any plan to port this component to Angular Typescript.
