### ISSUE TITLE
min time and max time

### ISSUE THREAD

**Issue by texperts** [beenote/angular-material-datetimepicker#60]
I need two inputs from user start and end dates, times..,
after selecting the start date and time I can able to disable end date to select before the start date but I am unable to disable end times which are before start time. 

@ViDaNgEr @beenoteadmin Let me know how the above issue can be achieved

**Comment by hexadecy** [comment]
@texperts for anything different than the demo "DateRange Example", you need to have a watcher to set a value to max-date and min-date.

Does the input is changed manually?
https://github.com/beenote/angular-material-datetimepicker/issues/38
