### ISSUE TITLE
Add mdDialog hasBackdrop option

### ISSUE THREAD

**Issue by brianmtully** [beenote/angular-material-datetimepicker#61]
Can you add the mdDialog hasBackdrop option to the directive? That would be very helpful. Thanks.

**Comment by hexadecy** [comment]
Ok I will do this.

**Comment by hexadecy** [comment]
@brianmtully can you test it?

**Comment by brianmtully** [comment]
Great! Yea I will test it. Thanks

**Comment by hexadecy** [comment]
Reopen if not ok
