### ISSUE TITLE
Add am/pm text customization

### ISSUE THREAD

**Issue by cimela** [beenote/angular-material-datetimepicker#62]
I need to customize AM and PM button for Korean project (오천 and 오후).
I already use mdcDefaultParams({lang: 'kr'}) and it's still the same.

Can you add some setting like okText or cancelText?

**Comment by hexadecy** [comment]
There is no {lang: 'kr'} in https://code.angularjs.org/1.7.7/i18n/ 
ko-kr? angular-locale_ko-kr.js

There is already amText and pmText, I updated the readme, so no new version is needed.

**Comment by cimela** [comment]
> There is no {lang: 'kr'} in https://code.angularjs.org/1.7.7/i18n/
> ko-kr? angular-locale_ko-kr.js
> 
> There is already amText and pmText, I updated the readme, so no new version is needed.

It works like a charm. I can remove my code to change text manually.
Thanks for the information.
