### ISSUE TITLE
Could not find a declaration

### ISSUE THREAD

**Issue by SilinaGeorge** [beenote/angular-material-datetimepicker#64]
I'm working with angular 8 and when I try to install via npm and import it:
`import { ngMaterialDatePicker } from "ng-material-datetimepicker";`

it says the following

Could not find a declaration file for module 'ng-material-datetimepicker'. 'XXXXX/node_modules/ng-material-datetimepicker/js/angular-material-datetimepicker.js' implicitly has an 'any' type.
  Try `npm install @types/ng-material-datetimepicker` if it exists or add a new declaration (.d.ts) file containing `declare module 'ng-material-datetimepicker';`

I tried to do this work around https://www.detroitlabs.com/blog/2018/02/28/adding-custom-type-definitions-to-a-third-party-library/

which got rid of the error, however when I ran my code, in the console i got the follow error

> Uncaught ReferenceError: angular is not defined
>     at Object.ngMaterialDatePicker (angular-material-datetimepicker.js:92)
>     at angular-material-datetimepicker.js:1296
>     at Object../node_modules/ng-material-datetimepicker/js/angular-material-datetimepicker.js (angular-material-datetimepicker.js:1302)
>

**Comment by hexadecy** [comment]
Sorry, it's for AngularJS 1.x no plan to port it to Angular TS 2+
