### ISSUE TITLE
Setting shortTime=true on a date picker shows AM/PM indicator

### ISSUE THREAD

**Issue by oliversalzburg** [beenote/angular-material-datetimepicker#65]
If you set `shortTime` to `true` on a date picker, you will get an AM/PM indicator in the header of the dialog.

We noticed this because we set `shortTime` through `mdcDefaultParams` after the locale has been determined.

To work around this issue, we set `shortTime` explicitly to `false` when we only want to pick a date anyway.

**Comment by hexadecy** [comment]
Ok I'll try to reproduce it.
date="true"
time="false"
what you have in mdcDefaultParams()?

**Comment by oliversalzburg** [comment]
```
mdcDefaultParams( {
	shortTime : true
} );
```

**Comment by hexadecy** [comment]
Can you test v1.19.0?

**Comment by oliversalzburg** [comment]
Works great. Thanks
