### ISSUE TITLE
Picker icons cause layout issues, show-icon enables too many options

### ISSUE THREAD

**Issue by oliversalzburg** [beenote/angular-material-datetimepicker#66]
The `show-icon` attribute causes a calendar or clock icon to be displayed next to the input element. Clicking this icon opens the picker. This is very convenient and I'd really like to enable this for a certain use case I have.

However, this also adds a _clear_ button to the input element, which can have unintended implications. In my case, I don't want the user to be able to remove the time value in the input. IMHO the picker icon and the clear icon should be configurable separately.

Additionally, when the picker is contained in an `md-input-container`, the `label` intersects with the picker icon, which originally lead me to try to prevent the element from being cleared by the user.

![image](https://user-images.githubusercontent.com/1658949/64432819-8fb65b80-d0bd-11e9-8a3b-4f2779b6fa9e.png)

Additionally, there's a `dtp-input` CSS class being used in some places, which appears to add a margin on the left of the `input` element that seems like it's inteded for the above mentioned icons to fit in. However, if you _don't_ apply the style and enable `show-icon`, the control still looks perfectly fine.

**Comment by hexadecy** [comment]
Ok I will add a show-clear option.

**Comment by hexadecy** [comment]
Option show-clear added in: 307a514b0e0eaeaf5da94d1752c9a68aa309c721 v1.19.1
The label should be normally above the input.
dtp-input can be override with a css like: `.dtp .dtp-input`

Can you provide me a full example? (code) or better jsFiddle.

**Comment by oliversalzburg** [comment]
https://codepen.io/oliversalzburg/pen/NWKyJrd should showcase the issue with the label intersecting with the picker icon.

Also notice that, when you remove the `.dtp-input`, it has no effect on how the input is rendererd, which lead me to believe the class is actually redundant.

Thanks for the `show-clear`! I'll test it out ASAP

**Comment by hexadecy** [comment]
It's because this picker needs the placeholder attribute.
```
doctype html
html(
	ng-csp
	ng-app="foo"
	)
	md-input-container.md-block
		label Start
		input.dtp-no-msclear.dtp-input.md-input(
			type="text"
			mdc-datetime-picker
			date="false"
			time="true"
			minutes="true"
			ng-model-options="{timezone: meeting.fair.timezone}"
			format="LT"
			edit-input="true"
			show-icon="true"
			ng-model="vm.meeting.start"
			placeholder="Enter time"
			)
```

**Comment by oliversalzburg** [comment]
> It's because this picker needs the placeholder attribute.

Oh yeah, that's much better 😀 Thanks for that. What about the `dtp-input` class though? It seems like it's not doing anything. And if you were to remove the `show-icon`, it even looks weird for being indented under the label.

![image](https://user-images.githubusercontent.com/1658949/64593735-dbfbe700-d3ae-11e9-93f7-90339273fb2a.png)

**Comment by oliversalzburg** [comment]
`show-clear` is working perfectly btw. Thanks again

**Comment by hexadecy** [comment]
Class like `.dtp-no-msclear` or `.dtp-input` are added by the datetime-picker component only when show-icon is `"true"`. Most of the code in this fork is for a special use case.
```doctype html
html(
	ng-csp
	ng-app="foo"
	)
	md-input-container.md-block
		label Start
		input(
			type="text"
			mdc-datetime-picker
			date="false"
			time="true"
			minutes="true"
			ng-model-options="{timezone: meeting.fair.timezone}"
			format="LT"
			edit-input="true"
			show-icon="false"
			ng-model="vm.meeting.start"
			)
```
Please check examples at: https://github.com/beenote/angular-material-datetimepicker/blob/gh-pages/index.html

**Comment by oliversalzburg** [comment]
Oh, I see. I just copied directly from https://beenote.github.io/angular-material-datetimepicker/ and didn't think the class would be added by the directive. Thanks
