### ISSUE TITLE
Month displayed is not the same as month view

### ISSUE THREAD

**Issue by Chilo92** [beenote/angular-material-datetimepicker#67]
Hi 

Thanks alot the for library i chose this one over the others cause of the customisable minutes. Users recently started complaining about this month view issue but i could not replicate it on my side, however today i went through your demo page and i see i can replicate the issue there.

When changing the month sometimes the month view does not update and stays on the same month until you navigate an extra time in the same direction eg. twice back and then one forward then it works.  In the image you can see above it shows August but the month view shows September even using the dropdown does not work. Please assist

![image](https://user-images.githubusercontent.com/20395009/64842595-ef9f8b80-d602-11e9-8e30-e1c94c484985.png)

**Comment by Chilo92** [comment]
Also not sure if it helps but it seems this issue only occurs when there is a mindate

**Comment by hexadecy** [comment]
You mean a maxdate now? I see the issue is with the virtualscroll that don't go up, but the correct date is selected.

**Comment by Chilo92** [comment]
Yes sorry meant maxdate. And yes I see what u mean by the virtual scroll is an issue.

**Comment by hexadecy** [comment]
I think it's a lot better with [v1.19.2](https://github.com/beenote/angular-material-datetimepicker/releases/tag/v1.19.2), can you test it?

**Comment by Chilo92** [comment]
Sorry for the late response but i published this version to our production site, and so far no complaints from the users so it seems to have worked. Thanks for the help and quick response.
Also some more information i got the other day, it seems the user that initially reported it his screen was zoomed in chrome like 80% or so as soon as he zoomed out the issue was fixed, but again like i said no issues reported so far and its been 3 days now.
