### ISSUE TITLE
Cannot set default values for all params of the directive.

### ISSUE THREAD

**Issue by johnvarv** [beenote/angular-material-datetimepicker#69]
#### Current behavior:

I can not set default values for all default attributes of the directive.

#### Expected behavior:

I should be able to set default values for all default attributes of the directive.

#### More info: 

I''m trying to set the some default params as stated on the documentation.

so in my `run` function I have this:

`mdcDefaultParams({ showIcon: true, minuteSteps: 1, editInput: true });`

Now, wherever I use the datetimepcker, while the step of the minutes is indeed the default I set on `run`, the `showIcon` and the `editInput` are not applied.

I checked the source code and indeed you set the passed params from `mdcDefaultParams` as default on the factory, but you do not check them and use them on the link function. You merge them and use them only on the `PluginController`, which is, as I understand only for the dialog.

I think it will be nice to be able to set defaults for showIcon, editInput etc.

**Comment by hexadecy** [comment]
The problem is that the mdcDefaultParams factory function override with its default value the attributes provided in the directive. 

I don't want to break the backward compatibility, but you can make a fork.
