### ISSUE TITLE
Support clearing date from dialog

### ISSUE THREAD

**Issue by norkunas** [beenote/angular-material-datetimepicker#70]
I am using `mdcDateTimeDialog` without an input. As there is no "clear button" in default template, I have customized it to have a "clear" button and providing that template to the service. But setting `picker.currentDate=null` breaks whole calendar. Or there is another way to clear it that I don't see?

**Comment by hexadecy** [comment]
You have to re-call initDates(), date time cannot be a null, it must be a moment date.

**Comment by norkunas** [comment]
It still doesn't give the required output :) managed to workaround this:
```html
<md-button
 ng-if="::picker.params.clearBtn"
 class="dtp-btn-today md-button"
 ng-click="picker.currentDate=null;picker.hide(true);picker.initDates()"
>
 Clear
</md-button>
```
