### ISSUE TITLE
unable to load datetime picker on dialog box.

### ISSUE THREAD

**Issue by lovepreetintugine** [beenote/angular-material-datetimepicker#71]
unable to load datetime picker on dialog box . but Its showing back side of dialog box.

**Comment by hexadecy** [comment]
What kind of dialog box? From angular material, which version, a code example?

**Comment by lovepreetintugine** [comment]
I am using a materialize design modals
materialize version - 1.0.0
modals code example - 
 <div id="editTrip" ng-show="editTrip" class="modal">
                    <div class="modal-content">
                       <md-input-container flex-gt-md="30">
        <label>Timepicker Only</label>
       <input mdc-datetime-picker="" date="true" time="true" type="text" id="datetimeedit"
placeholder="YYYY-MM-DD HH:MM" show-todays-date="" minutes="true" short-time="true"
min-date="minDate" max-date="maxDateNow" edit-input="true" show-icon="true" ng-model="dateTimeEdit"
name="datetimeedit" class=" dtp-no-msclear dtp-input md-input" >
    </md-input-container>
                    </div>
                </div>

**Comment by lovepreetintugine** [comment]
```
<div id="editTrip" ng-show="editTrip" class="modal">
    <div class="modal-content">
        <md-input-container flex-gt-md="30">
            <label>Timepicker Only</label>
            <input mdc-datetime-picker="" date="true" time="true" type="text" id="datetimeedit" placeholder="YYYY-MM-DD HH:MM" show-todays-date="" minutes="true" short-time="true" min-date="minDate" max-date="maxDateNow" edit-input="true" show-icon="true" ng-model="dateTimeEdit" name="datetimeedit" class=" dtp-no-msclear dtp-input md-input">
        </md-input-container>
    </div>
</div>
```

**Comment by hexadecy** [comment]
It's build to be used with `<md-dialog>` from [AngularJS Material 1.1.x](https://material.angularjs.org/latest/demo/dialog)

**Comment by hexadecy** [comment]
Please make a fork if you want to use it with another framework.
