### ISSUE TITLE
ng-change not being triggered as expected and validation failing

### ISSUE THREAD

**Issue by cgarveyie** [beenote/angular-material-datetimepicker#72]
**Assumptions**
format set to something like: DD.MM.YYYY HH:mm
ng-message="format" validation message
ng-change=[expression] set

**To duplicate this bug follow the steps below:**

1. Use the dialog to populate the field such that it reads "03.03.2020 4:23 PM" or similar
2. Click into the field and manually remove the "PM" suffix so it reads "03.03.2020 4:23" 
3. Validation message appears
4. Use the calendar widget to select another date/time
5. Field is populated with the new value 

BUG
Validation message remains
ng-change not triggered

**Comment by hexadecy** [comment]
It should works, make sure you have the correct `format="DD.MM.YYYY HH:mm A"` and `short-time="true"`

            <md-input-container>
              <label>Date/Time Picker edit input</label>
              <input mdc-datetime-picker date="true" time="true" type="text" id="datetimeedit" 
                  format="DD.MM.YYYY HH:mm A" placeholder="DD.MM.YYYY HH:mm PM" short-time="true"
                    show-todays-date minutes="true"
                    min-date="minDate" max-date="maxDateNow" edit-input="true" show-icon="true"
                    ng-model="dateTimeEdit" name="datetimeedit">
            </md-input-container>
            <div ng-messages="frm.datetimeedit.$error" style="color:red" role="alert">
              <div ng-message="format">invalid date format</div>
              <div ng-message="min">less than min date</div>
              <div ng-message="max">greater than max date</div>
            </div>
          </div>

**Comment by cgarveyie** [comment]
I'm afraid that isn't working. The format set is: DD.MM.YYYY h:mm A
This generates a string like: 05.03.2020 1:20 PM
If you remove the "M" at the end of the string the validation doesn't trigger an error.
Removing the "P" as well does trigger the format validation message.

Video attached demonstrating the issue
[angular-material-datetimepickeri-ssue72.zip](https://github.com/beenote/angular-material-datetimepicker/files/4293261/angular-material-datetimepickeri-ssue72.zip)

**Comment by hexadecy** [comment]
The library used behind the scene is Moment.js

a A | am pm | Post or ante meridiem (Note the one character a p are also considered valid)
-- | -- | --

So it's a valid date.

**Comment by cgarveyie** [comment]
My point is that when the date is populated by the widget with a valid date the error message remains.
A user shouldn't have to manually click into the input field and add/delete a character to trigger the validation check.

**Comment by hexadecy** [comment]
The error message disappears in the demo id="datetimeedit". 
Maybe because you use an external ng-change, then you have to add a watcher for it.
I don't want to add other watchers included in the widget as some use cases don't need it.
