### ISSUE TITLE
If ng-disabled is true. Input field is disabled but buttons are not

### ISSUE THREAD

**Issue by cgarveyie** [beenote/angular-material-datetimepicker#73]
Pretty much as the title suggests. For a picker with the calendarWidget enabled, only the input field is disabled. The open widget and clear buttons are not disabled

**Comment by hexadecy** [comment]
Can you check it works? with version 1.19.4

**Comment by cgarveyie** [comment]
Hi hexadecy and thanks for looking at this so quickly.

It works if you pass in "true" or "false" as a string value for ngDisabled but if you pass in an expression which resolves to true or false it doesn't work. 

My own use case is that I want to dynamically enable/disable the date time picker depending on whether or not an event is being scheduled  so for me this solution is incomplete.
e.g.
`ngDisabled = "vm.eventData.isScheduled !== 'scheduled'"`
resolves to false unless the isScheduled SELECT list is scheduled.

I played with it a bit as follows:

```
// Evaluate the value
var isDisabled = scope.$eval(attrs.ngDisabled);

// Keep it DRY
(isDisabled ? 'disabled ' : '')
```
This fixes the evaluation issue but unlike the inputfield, the buttons aren't updated if the expression value changes.

**Comment by hexadecy** [comment]
Sorry, I have no idea right now how to make it dynamic.

**Comment by hexadecy** [comment]
Stalled issue
