### ISSUE TITLE
Date part is lost when editing time

### ISSUE THREAD

**Issue by oliversalzburg** [beenote/angular-material-datetimepicker#75]
If you use a datetimepicker to only edit the time of a moment instance and that moment instant is for any other day than today, editing the time will reset it to the current day.

That is simply because https://github.com/beenote/angular-material-datetimepicker/blob/gh-pages/js/angular-material-datetimepicker.js#L218 only parses the time value and then loses any date that is stored in the current model.

**Comment by hexadecy** [comment]
Can you submit a PR?

**Comment by oliversalzburg** [comment]
I guess I really should, but I was in such a hurry when I noticed the issue that I didn't get a good grip on the source of the issue.

I believe the root cause was https://github.com/beenote/angular-material-datetimepicker/blob/gh-pages/js/angular-material-datetimepicker.js#L224 where `.toDate()` is called, making the model value a `Date` and not a `moment`. I don't understand the purpose of this line, because converting to `Date` seems to be the opposite of what you'd want when interacting with Moment instances.

Maybe you can shed some light on this and help me understand the purpose. I'll try to provide a PR for it, but we already have a workaround in our code base by aggressivly converting the model value back to a Moment instance in a watcher.

**Comment by hexadecy** [comment]
The toDate() is used only for a legacy reason and I don't want to add a breaking change.

**Comment by oliversalzburg** [comment]
This'll get way too complicated for me to fix upstream. I'll just leave a workaround here in case someone has the same problem in the future:
```js
__reconstructMoment( date, time ) {
	const year      = moment( date ).year();
	const dayOfYear = moment( date ).dayOfYear();

	return moment( time )
		.year( year )
		.dayOfYear( dayOfYear );
}

$scope.$watch( "vm.meetingStartTime", () => {
	vm.meeting.start = vm.__reconstructMoment( vm.meetingStartDate, vm.meetingStartTime );
} );
```
