### ISSUE TITLE
Option to edit both date and time at the same time on dialog?

### ISSUE THREAD

**Issue by Thaina** [beenote/angular-material-datetimepicker#77]
Is it possible to show both clock and calendar at the same time?

And if possible, I wish there would be a simple mode. With number picker for year/minute/second and dropdown for date/month/hour. And could make a combination of simpledate/fullclock or calendar/simpleclock

**Comment by hexadecy** [comment]
There is no option for that.

Templates have to be modified in the code, probably safer to fork this project.
