### ISSUE TITLE
User cannot use blue bubble on the clock to set time on Firefox

### ISSUE THREAD

**Issue by valentin-tkachev** [beenote/angular-material-datetimepicker#88]
If users select the blue bubble on the clock and keep their mouse cursor pressed down to move the hour or minute, they are refreshed the page. This is only happening on the Firefox browser.

The user is able to select the hour or minute hand and move it around with no issues. 

Steps To Reproduce:

1. Open Timepicker
2. When setting the time, left-click the blue bubble on the hour, keep the mouse button pressed and attempt to move the bubble to another time
3. Release the mouse button and observe results

https://user-images.githubusercontent.com/72623892/147273011-e8d4db93-3c85-45f7-9f0b-785f8f95103a.mov

**Comment by hexadecy** [comment]
Should be fixed for all clickable elements.
