### ISSUE TITLE
Min/max date comparison is apparently not timezone-safe

### ISSUE THREAD

**Issue by oliversalzburg** [beenote/angular-material-datetimepicker#91]
Nice to see this project is still being maintained so many years later :D

One of our users is in GMT-8 and was handling GMT+2 dates in the calendar. Due to the comparison being done in https://github.com/beenote/angular-material-datetimepicker/blob/gh-pages/js/angular-material-datetimepicker.js#L454-L486 this resulted in not all expected dates be shown on the calendar.

I can produce a minimal example if it is necessary, but I noticed something about the quoted code section. Why is it not just using `moment().isAfter()`? This should be much safer as time zones should probably be correctly respected in that method.

**Comment by oliversalzburg** [comment]
After looking at the repo now, I see there's an option `ng-model-options="{timezone: 'utc'}"` that I was not aware of. Maybe this might be a non-issue if we had that in our code.

**Comment by hexadecy** [comment]
Yes you have to use this options. This library was first built to be used with the browser's local time only.
